### ISSUE TITLE
Foreign Object Relationships: Concern - When deleting foreign object the native object throws errors

### ISSUE THREAD

**Issue by kgaylord** [AugerArchitecture/P2P#18]
In "Full Application" (as opposed to "Thumbnail Plan") mode the following occurs:

```
Using the SoftCo/ServiceCo/Joint Offer model:
    All functions under "Modeling" and "Performance" do not come up....do not appear
        In addition, when in Full Application mode trying to access Modeling and Performance you        cannot change the offering...I imagine they are linked?
```

**Comment by karlonauger** [comment]
This issue has caused the breaking of Computed Models and Graphs on the Modeling and Performance tabs

**Comment by karlonauger** [comment]
Fixed: By breaking functions (returning null) whenever a foreign object is needed and is null. 

Note: The Project Model now states "Warning" if the project model item's foreign object cannot be found.
          To fix this "Warning" please delete and recreate that project model item.
